/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Endpoint de salud para monitoring y Docker HEALTHCHECK. No requiere autenticación.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login With Google */
        post: operations["login_with_google_api_v1_auth_google_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entries/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Entries */
        get: operations["list_entries_api_v1_entries__get"];
        put?: never;
        /** Create Entry */
        post: operations["create_entry_api_v1_entries__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entries/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Entry */
        get: operations["get_entry_api_v1_entries__entry_id__get"];
        /** Update Entry */
        put: operations["update_entry_api_v1_entries__entry_id__put"];
        post?: never;
        /** Delete Entry */
        delete: operations["delete_entry_api_v1_entries__entry_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entries/{entry_id}/cover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Cover Image */
        post: operations["upload_cover_image_api_v1_entries__entry_id__cover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entries/{entry_id}/progress/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Progress */
        post: operations["reset_progress_api_v1_entries__entry_id__progress_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entries/{entry_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update Progress */
        post: operations["update_progress_api_v1_entries__entry_id__progress_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entries/{entry_id}/progress/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Progress History */
        get: operations["get_progress_history_api_v1_entries__entry_id__progress_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Profile */
        patch: operations["update_profile_api_v1_users_me_patch"];
        trace?: never;
    };
    "/api/v1/users/me/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Avatar */
        post: operations["upload_avatar_api_v1_users_me_avatar_post"];
        /** Delete Avatar */
        delete: operations["delete_avatar_api_v1_users_me_avatar_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/external/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search External */
        get: operations["search_external_api_v1_external_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/external/games/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Game Detail
         * @description Obtiene el detalle de un juego desde RAWG.
         *
         *     El listado de búsqueda (`/external/search`) no trae el `playtime` de RAWG,
         *     así que el frontend hace esta llamada adicional cuando el usuario
         *     selecciona un juego de los resultados de autocompletado (lazy fetch).
         *     El objetivo es precargar `progress_total` para el tipo `game`.
         *
         *     El endpoint degrada con elegancia: si RAWG no está configurado o el
         *     juego no existe, devuelve `playtime_raw=None` y `playtime_hours=None`
         *     para que el frontend no rompa el flujo de autocompletado.
         */
        get: operations["get_game_detail_api_v1_external_games__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Pairing Code
         * @description Genera un código de emparejamiento para vincular un dispositivo externo.
         *
         *     El código tiene 6 caracteres alfanuméricos y expira en 5 minutos.
         *     Requiere autenticación JWT desde la SPA.
         */
        post: operations["generate_pairing_code_api_v1_devices_pair_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activate Device
         * @description Activa un dispositivo usando un código de emparejamiento.
         *
         *     No requiere autenticación (el código es el mecanismo de autenticación).
         *     Devuelve el device_token que se debe guardar en el dispositivo.
         *     El token solo se muestra UNA VEZ.
         */
        post: operations["activate_device_api_v1_devices_activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Devices
         * @description Lista todos los dispositivos emparejados activos del usuario.
         *
         *     Requiere autenticación JWT desde la SPA.
         */
        get: operations["list_devices_api_v1_devices__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke Device
         * @description Revoca un dispositivo emparejado. El token dejará de funcionar inmediatamente.
         *
         *     Requiere autenticación JWT desde la SPA.
         */
        delete: operations["revoke_device_api_v1_devices__device_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/import/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse Import
         * @description Parsea una lista de contenido con Claude/Bedrock.
         *
         *     **Fuentes soportadas:**
         *     - `mal`: MyAnimeList (XML o HTML)
         *     - `anilist`: AniList (JSON export)
         *     - `kitsu`: Kitsu (JSON export)
         *     - `steam`: Steam (lista de juegos)
         *     - `text`: Texto libre
         *
         *     **Nota:** Este endpoint consume tokens de Bedrock (~5-15k por lista de 100 entradas).
         */
        post: operations["parse_import_api_v1_import_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/import/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute Import
         * @description Ejecuta la importación de entradas parseadas.
         *
         *     Crea las entradas en batch dentro de una transacción.
         *     Las entradas duplicadas (por título) se omiten automáticamente.
         */
        post: operations["execute_import_api_v1_import_execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Recommendations
         * @description Genera recomendaciones personalizadas con Claude/Bedrock.
         *
         *     Analiza la colección completa del usuario (ratings, tipos, estados) y
         *     sugiere obras nuevas basadas en sus patrones de consumo.
         *
         *     **Nota:** Este endpoint consume tokens de Bedrock (~30-50k por generación).
         *
         *     **Requisito mínimo:** 5 entradas en la colección para resultados óptimos.
         */
        post: operations["generate_recommendations_api_v1_recommendations_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stats Overview
         * @description Obtiene estadísticas completas del usuario.
         *
         *     Incluye:
         *     - Total de entradas por tipo y estado
         *     - Ratings promedio globales y por tipo
         *     - Tasas de completado
         *     - Distribución de ratings
         *     - Progreso acumulado
         *     - Timeline de entradas añadidas
         *     - Racha de actualizaciones
         *
         *     **Performance**: Optimizado para <100ms con hasta 1000 entradas.
         */
        get: operations["get_stats_overview_api_v1_stats_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description Envía un mensaje a GlyphAI y recibe la respuesta en streaming (SSE).
         *
         *     Formato de eventos:
         *     ```
         *     data: {"delta": "texto"}
         *
         *
         *     ...
         *     data: [DONE]
         *
         *
         *     ```
         *
         *     El mensaje del usuario y la respuesta (completa o parcial si hay error)
         *     se persisten en la conversación indicada, o en una nueva si no se indica.
         */
        post: operations["chat_api_v1_ai_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Conversations
         * @description Lista las conversaciones del usuario, ordenadas por `updated_at DESC`.
         *
         *     Excluye conversaciones huérfanas (sin mensajes).
         */
        get: operations["list_conversations_api_v1_ai_conversations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Conversation
         * @description Detalle de una conversación propia con todos sus mensajes.
         */
        get: operations["get_conversation_api_v1_ai_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Conversation
         * @description Elimina una conversación propia (cascada a sus mensajes).
         */
        delete: operations["delete_conversation_api_v1_ai_conversations__conversation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivateDeviceRequest
         * @description Solicitud para activar un dispositivo con un código de emparejamiento.
         */
        ActivateDeviceRequest: {
            /** Pairing Code */
            pairing_code: string;
            /** Device Name */
            device_name: string;
        };
        /**
         * ActivateDeviceResponse
         * @description Respuesta al activar un dispositivo. Contiene el token en texto plano (única vez).
         */
        ActivateDeviceResponse: {
            /**
             * Device Token
             * @description Token de acceso. Solo se muestra una vez.
             */
            device_token: string;
            /**
             * Device Id
             * Format: uuid
             */
            device_id: string;
            /** Device Name */
            device_name: string;
        };
        /** AvatarUploadResponse */
        AvatarUploadResponse: {
            /** Avatar Url */
            avatar_url: string;
        };
        /** Body_create_entry_api_v1_entries__post */
        Body_create_entry_api_v1_entries__post: {
            /** Cover Image */
            cover_image?: string | null;
            /**
             * Title
             * @default
             */
            title: string;
            /** Type */
            type: string;
            /** Status */
            status: string;
            /** Rating */
            rating?: string | null;
            /** Year */
            year?: string | null;
            /** Notes */
            notes?: string | null;
            /** Cover Image Url */
            cover_image_url?: string | null;
            /** Progress Unit */
            progress_unit?: string | null;
            /** Progress Total */
            progress_total?: string | null;
        };
        /** Body_upload_avatar_api_v1_users_me_avatar_post */
        Body_upload_avatar_api_v1_users_me_avatar_post: {
            /** Avatar */
            avatar: string;
        };
        /** Body_upload_cover_image_api_v1_entries__entry_id__cover_post */
        Body_upload_cover_image_api_v1_entries__entry_id__cover_post: {
            /** Cover Image */
            cover_image: string;
        };
        /**
         * ChatMessage
         * @description Mensaje individual del historial de chat enviado por el cliente.
         */
        ChatMessage: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant" | "system";
            /** Content */
            content: string;
        };
        /**
         * ChatMessageResponse
         * @description Mensaje persistido devuelto por la API.
         */
        ChatMessageResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant" | "system";
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ChatRequest
         * @description Request de chat: historial de mensajes + conversación persistente opcional.
         *
         *     Si `conversation_id` se omite, se crea una conversación nueva y tanto el
         *     mensaje del usuario como la respuesta se persisten en ella. El widget
         *     flotante (efímero) no envía `conversation_id`.
         */
        ChatRequest: {
            /** Messages */
            messages: components["schemas"]["ChatMessage"][];
            /** Conversation Id */
            conversation_id?: string | null;
        };
        /**
         * ConversationListItem
         * @description Item del listado de conversaciones (sidebar de /chat).
         */
        ConversationListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ConversationResponse
         * @description Conversación completa con todos sus mensajes.
         */
        ConversationResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Messages */
            messages: components["schemas"]["ChatMessageResponse"][];
        };
        /**
         * DeviceListResponse
         * @description Lista de dispositivos emparejados del usuario.
         */
        DeviceListResponse: {
            /** Devices */
            devices: components["schemas"]["DeviceResponse"][];
        };
        /**
         * DeviceResponse
         * @description Respuesta con información de un dispositivo emparejado.
         */
        DeviceResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Device Name */
            device_name: string;
            /** Last Used At */
            last_used_at: string | null;
            /** Is Revoked */
            is_revoked: boolean;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * EntryListItem
         * @description Schema para ítems del listado de colección.
         *
         *     Excluye user_id por decisión de diseño: en el listado propio del usuario
         *     autenticado no es necesario exponer el identificador interno.
         */
        EntryListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            type: components["schemas"]["EntryType"];
            status: components["schemas"]["EntryStatus"];
            /** Rating */
            rating: number | null;
            /** Cover Image */
            cover_image: string | null;
            progress_unit?: components["schemas"]["ProgressUnit"] | null;
            /** Progress Total */
            progress_total?: number | null;
            /** Current Progress */
            current_progress?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** EntryResponse */
        EntryResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Title */
            title: string;
            type: components["schemas"]["EntryType"];
            status: components["schemas"]["EntryStatus"];
            /** Rating */
            rating: number | null;
            /** Year */
            year: number | null;
            /** Notes */
            notes: string | null;
            /** Cover Image */
            cover_image: string | null;
            progress_unit: components["schemas"]["ProgressUnit"] | null;
            /** Progress Total */
            progress_total: number | null;
            /** Current Progress */
            current_progress: number | null;
            /**
             * Has History
             * @default false
             */
            has_history: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * EntryStatus
         * @enum {string}
         */
        EntryStatus: "watching" | "completed" | "on_hold" | "dropped" | "plan_to_watch";
        /**
         * EntryType
         * @enum {string}
         */
        EntryType: "anime" | "manga" | "game";
        /** EntryUpdate */
        EntryUpdate: {
            /** Title */
            title?: string | null;
            type?: components["schemas"]["EntryType"] | null;
            status?: components["schemas"]["EntryStatus"] | null;
            /** Rating */
            rating?: number | null;
            /** Year */
            year?: number | null;
            /** Notes */
            notes?: string | null;
            /** Cover Image */
            cover_image?: string | null;
            progress_unit?: components["schemas"]["ProgressUnit"] | null;
            /** Progress Total */
            progress_total?: number | null;
            /** Current Progress */
            current_progress?: number | null;
        };
        /** ExternalSearchResponse */
        ExternalSearchResponse: {
            /** Results */
            results: components["schemas"]["ExternalSearchResult"][];
        };
        /** ExternalSearchResult */
        ExternalSearchResult: {
            /** Title */
            title: string;
            /** Year */
            year?: number | null;
            /** Cover Image */
            cover_image?: string | null;
            type: components["schemas"]["EntryType"];
            /** Source */
            source: string;
            /** Progress Total */
            progress_total?: string | null;
            /** Slug */
            slug?: string | null;
        };
        /**
         * GameDetailResponse
         * @description Respuesta del endpoint de detalle de un juego externo (RAWG).
         *
         *     `playtime_raw` es el campo original de RAWG en minutos.
         *     `playtime_hours` es la conversión a Decimal con 2 decimales para usar
         *     directamente como `progress_total` en horas (unidad fija de games).
         */
        GameDetailResponse: {
            /** Slug */
            slug: string;
            /** Playtime Raw */
            playtime_raw?: number | null;
            /** Playtime Hours */
            playtime_hours?: string | null;
        };
        /**
         * GenerateRecommendationsRequest
         * @description Request para generar recomendaciones.
         */
        GenerateRecommendationsRequest: {
            /** @description Filtrar por tipo */
            type?: components["schemas"]["EntryType"] | null;
            /**
             * Limit
             * @description Número de recomendaciones
             * @default 10
             */
            limit: number;
        };
        /**
         * GenerateRecommendationsResponse
         * @description Response de generación de recomendaciones.
         */
        GenerateRecommendationsResponse: {
            /**
             * Recommendations
             * @description Recomendaciones
             */
            recommendations: components["schemas"]["Recommendation"][];
            /** @description Metadata */
            metadata: components["schemas"]["RecommendationMetadata"];
        };
        /** GoogleLoginRequest */
        GoogleLoginRequest: {
            /** Id Token */
            id_token: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ImportError
         * @description Error al importar una entrada.
         */
        ImportError: {
            /**
             * Title
             * @description Título de la entrada con error
             */
            title: string;
            /**
             * Error
             * @description Mensaje de error
             */
            error: string;
        };
        /**
         * ImportExecuteRequest
         * @description Request para ejecutar la importación.
         */
        ImportExecuteRequest: {
            /**
             * Entries
             * @description Entradas a importar (máx 500)
             */
            entries: components["schemas"]["ParsedEntry-Input"][];
        };
        /**
         * ImportExecuteResponse
         * @description Response de la ejecución de importación.
         */
        ImportExecuteResponse: {
            /**
             * Created
             * @description Número de entradas creadas
             */
            created: number;
            /**
             * Skipped
             * @description Número de entradas omitidas
             */
            skipped: number;
            /**
             * Errors
             * @description Errores al importar
             */
            errors?: components["schemas"]["ImportError"][];
        };
        /**
         * ImportParseRequest
         * @description Request para parsear una lista de importación.
         */
        ImportParseRequest: {
            /** @description Fuente de la lista */
            source: components["schemas"]["ImportSource"];
            /**
             * Content
             * @description Contenido de la lista
             */
            content: string;
        };
        /**
         * ImportParseResponse
         * @description Response del parseo de importación.
         */
        ImportParseResponse: {
            /**
             * Entries
             * @description Entradas parseadas
             */
            entries: components["schemas"]["ParsedEntry-Output"][];
            /**
             * Warnings
             * @description Advertencias del parseo
             */
            warnings?: string[];
        };
        /**
         * ImportSource
         * @description Fuentes soportadas para importación.
         * @enum {string}
         */
        ImportSource: "mal" | "anilist" | "kitsu" | "steam" | "text";
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * PaginatedConversationsResponse
         * @description Respuesta paginada de conversaciones (mismo formato que entries).
         */
        PaginatedConversationsResponse: {
            /** Conversations */
            conversations: components["schemas"]["ConversationListItem"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Limit */
            limit: number;
            /** Total Pages */
            total_pages: number;
        };
        /** PaginatedEntryResponse */
        PaginatedEntryResponse: {
            /** Entries */
            entries: components["schemas"]["EntryListItem"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Limit */
            limit: number;
            /** Total Pages */
            total_pages: number;
        };
        /**
         * PaginatedProgressHistoryResponse
         * @description Schema para la respuesta paginada del historial de progreso.
         */
        PaginatedProgressHistoryResponse: {
            /** Events */
            events: components["schemas"]["ProgressEventResponse"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /**
             * Has More
             * @default false
             */
            has_more: boolean;
        };
        /**
         * PairingCodeResponse
         * @description Respuesta al generar un código de emparejamiento.
         */
        PairingCodeResponse: {
            /** Pairing Code */
            pairing_code: string;
            /**
             * Expires In
             * @description Segundos hasta que expire el código
             */
            expires_in: number;
        };
        /**
         * ParsedEntry
         * @description Entrada parseada por Claude desde una lista externa.
         */
        "ParsedEntry-Input": {
            /**
             * Title
             * @description Título de la obra
             */
            title: string;
            /** @description Tipo de entrada */
            type: components["schemas"]["EntryType"];
            /** @description Estado de seguimiento */
            status: components["schemas"]["EntryStatus"];
            /**
             * Rating
             * @description Rating de 1 a 10
             */
            rating?: number | null;
            /**
             * Current Progress
             * @description Progreso actual
             */
            current_progress?: number | string | null;
            /**
             * Progress Total
             * @description Progreso total
             */
            progress_total?: number | string | null;
            /**
             * Year
             * @description Año de lanzamiento
             */
            year?: number | null;
            /**
             * Notes
             * @description Notas del usuario
             */
            notes?: string | null;
            /**
             * Confidence
             * @description Confianza del parseo (0.0-1.0)
             */
            confidence: number;
        };
        /**
         * ParsedEntry
         * @description Entrada parseada por Claude desde una lista externa.
         */
        "ParsedEntry-Output": {
            /**
             * Title
             * @description Título de la obra
             */
            title: string;
            /** @description Tipo de entrada */
            type: components["schemas"]["EntryType"];
            /** @description Estado de seguimiento */
            status: components["schemas"]["EntryStatus"];
            /**
             * Rating
             * @description Rating de 1 a 10
             */
            rating?: number | null;
            /**
             * Current Progress
             * @description Progreso actual
             */
            current_progress?: string | null;
            /**
             * Progress Total
             * @description Progreso total
             */
            progress_total?: string | null;
            /**
             * Year
             * @description Año de lanzamiento
             */
            year?: number | null;
            /**
             * Notes
             * @description Notas del usuario
             */
            notes?: string | null;
            /**
             * Confidence
             * @description Confianza del parseo (0.0-1.0)
             */
            confidence: number;
        };
        /**
         * ProgressEventResponse
         * @description Schema de respuesta para un evento de progreso.
         */
        ProgressEventResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Entry Id
             * Format: uuid
             */
            entry_id: string;
            /** Previous Value */
            previous_value: number | null;
            /** Current Value */
            current_value: number;
            unit: components["schemas"]["ProgressUnit"];
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /** Note */
            note: string | null;
            /** Source */
            source: string;
            event_type: components["schemas"]["ProgressEventType"];
            /** User Id */
            user_id: string | null;
            /**
             * Delta
             * @description Diferencia entre el valor actual y el anterior.
             */
            readonly delta: number | null;
        };
        /**
         * ProgressEventType
         * @enum {string}
         */
        ProgressEventType: "update" | "reset";
        /**
         * ProgressResetRequest
         * @description Schema para solicitar el reinicio del seguimiento de una entrada.
         */
        ProgressResetRequest: {
            /** Reason */
            reason?: string | null;
            /** New Type */
            new_type?: string | null;
            /** New Progress Total */
            new_progress_total?: number | null;
        };
        /**
         * ProgressUnit
         * @enum {string}
         */
        ProgressUnit: "episodes" | "chapters" | "volumes" | "minutes" | "percentage" | "hours";
        /**
         * ProgressUpdateRequest
         * @description Schema para actualizar manualmente el progreso.
         */
        ProgressUpdateRequest: {
            /** New Value */
            new_value: number;
            /** Note */
            note?: string | null;
            /**
             * Mark Completed
             * @default false
             */
            mark_completed: boolean;
        };
        /**
         * Recommendation
         * @description Recomendación generada por Claude.
         */
        Recommendation: {
            /**
             * Title
             * @description Título de la obra
             */
            title: string;
            /** @description Tipo de entrada */
            type: components["schemas"]["EntryType"];
            /**
             * Match Percentage
             * @description Porcentaje de match (0-100)
             */
            match_percentage: number;
            /**
             * Reason
             * @description Razón de la recomendación
             */
            reason: string;
            /**
             * Genres
             * @description Géneros
             */
            genres?: string[];
            /**
             * Year
             * @description Año
             */
            year?: number | null;
            /**
             * External Url
             * @description URL externa (AniList/RAWG)
             */
            external_url?: string | null;
            /**
             * Cover Image Url
             * @description URL de la imagen de portada
             */
            cover_image_url?: string | null;
            /**
             * Similar To
             * @description Títulos similares de la colección
             */
            similar_to?: string[];
        };
        /**
         * RecommendationMetadata
         * @description Metadata de la generación de recomendaciones.
         */
        RecommendationMetadata: {
            /**
             * Analyzed Entries
             * @description Entradas analizadas
             */
            analyzed_entries: number;
            /**
             * Favorite Genres
             * @description Géneros favoritos
             */
            favorite_genres?: string[];
            /**
             * Avg Rating
             * @description Rating promedio
             */
            avg_rating: number;
            /**
             * Completion Rate
             * @description Tasa de completado (%)
             */
            completion_rate: number;
            /**
             * Tokens Used
             * @description Tokens consumidos
             */
            tokens_used?: number | null;
            /**
             * Model
             * @description Modelo usado
             */
            model: string;
        };
        /** RegisterResponse */
        RegisterResponse: {
            user: components["schemas"]["UserResponse"];
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * SortField
         * @enum {string}
         */
        SortField: "created_at" | "title" | "rating";
        /**
         * SortOrder
         * @enum {string}
         */
        SortOrder: "asc" | "desc";
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserCreate */
        UserCreate: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** UserProfileResponse */
        UserProfileResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Username */
            username: string | null;
            /** Avatar Url */
            avatar_url: string;
            /** Bio */
            bio: string | null;
        };
        /** UserProfileUpdate */
        UserProfileUpdate: {
            /**
             * Username
             * @description Nombre de usuario público. Alfanumérico + underscore, 3-20 chars.
             */
            username?: string | null;
            /**
             * Bio
             * @description Biografía pública del usuario. Máximo 500 caracteres.
             */
            bio?: string | null;
        };
        /** UserResponse */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
        };
        /**
         * UserStats
         * @description Estadísticas completas del usuario.
         * @example {
         *       "avg_rating": 8.2,
         *       "avg_rating_by_type": {
         *         "anime": 8.5,
         *         "game": 8.3,
         *         "manga": 7.8
         *       },
         *       "by_status": {
         *         "completed": 30,
         *         "dropped": 2,
         *         "on_hold": 3,
         *         "plan_to_watch": 5,
         *         "watching": 5
         *       },
         *       "by_type": {
         *         "anime": 20,
         *         "game": 10,
         *         "manga": 15
         *       },
         *       "completion_rate": 66.7,
         *       "completion_rate_by_type": {
         *         "anime": 70,
         *         "game": 70,
         *         "manga": 60
         *       },
         *       "current_streak_days": 7,
         *       "entries_by_month": [
         *         [
         *           "2025-08",
         *           3
         *         ],
         *         [
         *           "2025-09",
         *           5
         *         ],
         *         [
         *           "2025-10",
         *           2
         *         ]
         *       ],
         *       "rating_distribution": {
         *         "1": 0,
         *         "2": 0,
         *         "3": 1,
         *         "4": 2,
         *         "5": 3,
         *         "6": 5,
         *         "7": 8,
         *         "8": 12,
         *         "9": 10,
         *         "10": 4
         *       },
         *       "top_genres": [
         *         [
         *           "Action",
         *           15
         *         ],
         *         [
         *           "Fantasy",
         *           12
         *         ],
         *         [
         *           "Adventure",
         *           10
         *         ]
         *       ],
         *       "total_entries": 45,
         *       "total_progress": {
         *         "chapters": 350,
         *         "episodes": 240,
         *         "hours": 120.5
         *       }
         *     }
         */
        UserStats: {
            /**
             * Total Entries
             * @description Total de entradas
             */
            total_entries: number;
            /**
             * By Type
             * @description Entradas por tipo (anime/manga/game)
             */
            by_type: {
                [key: string]: number;
            };
            /**
             * By Status
             * @description Entradas por estado (watching/completed/etc)
             */
            by_status: {
                [key: string]: number;
            };
            /**
             * Avg Rating
             * @description Rating promedio global
             */
            avg_rating: number;
            /**
             * Avg Rating By Type
             * @description Rating promedio por tipo
             */
            avg_rating_by_type: {
                [key: string]: number;
            };
            /**
             * Completion Rate
             * @description Porcentaje de entradas completadas
             */
            completion_rate: number;
            /**
             * Completion Rate By Type
             * @description Porcentaje de completado por tipo
             */
            completion_rate_by_type: {
                [key: string]: number;
            };
            /**
             * Top Genres
             * @description Top 10 géneros más frecuentes (nombre, count)
             */
            top_genres: [
                string,
                number
            ][];
            /**
             * Rating Distribution
             * @description Distribución de ratings (1-10 -> count)
             */
            rating_distribution: {
                [key: string]: number;
            };
            /**
             * Total Progress
             * @description Progreso acumulado por unidad (episodes/chapters/hours)
             */
            total_progress: {
                [key: string]: number;
            };
            /**
             * Entries By Month
             * @description Entradas añadidas por mes (YYYY-MM, count) - últimos 12 meses
             */
            entries_by_month: [
                string,
                number
            ][];
            /**
             * Current Streak Days
             * @description Días consecutivos con actualizaciones de progreso
             */
            current_streak_days: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_with_google_api_v1_auth_google_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_entries_api_v1_entries__get: {
        parameters: {
            query?: {
                type?: components["schemas"]["EntryType"] | null;
                search?: string | null;
                sort_by?: components["schemas"]["SortField"];
                sort_order?: components["schemas"]["SortOrder"];
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedEntryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_entry_api_v1_entries__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_entry_api_v1_entries__post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_entry_api_v1_entries__entry_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_entry_api_v1_entries__entry_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_entry_api_v1_entries__entry_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_cover_image_api_v1_entries__entry_id__cover_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_cover_image_api_v1_entries__entry_id__cover_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_progress_api_v1_entries__entry_id__progress_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProgressResetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_progress_api_v1_entries__entry_id__progress_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProgressUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_progress_history_api_v1_entries__entry_id__progress_history_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProgressHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
        };
    };
    update_profile_api_v1_users_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_avatar_api_v1_users_me_avatar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_avatar_api_v1_users_me_avatar_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvatarUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_avatar_api_v1_users_me_avatar_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
        };
    };
    search_external_api_v1_external_search_get: {
        parameters: {
            query: {
                /** @description Query de búsqueda para el catálogo externo */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_game_detail_api_v1_external_games__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_pairing_code_api_v1_devices_pair_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairingCodeResponse"];
                };
            };
        };
    };
    activate_device_api_v1_devices_activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivateDeviceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivateDeviceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_devices_api_v1_devices__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceListResponse"];
                };
            };
        };
    };
    revoke_device_api_v1_devices__device_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_import_api_v1_import_parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportParseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportParseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_import_api_v1_import_execute_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportExecuteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportExecuteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_recommendations_api_v1_recommendations_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRecommendationsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateRecommendationsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_overview_api_v1_stats_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserStats"];
                };
            };
        };
    };
    chat_api_v1_ai_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversations_api_v1_ai_conversations_get: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedConversationsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_api_v1_ai_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_conversation_api_v1_ai_conversations__conversation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
