"""add_device_tokens_table

Revision ID: aff87fa854fe
Revises: c2d0c6a36954
Create Date: 2026-07-18 17:45:29.313342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aff87fa854fe'
down_revision: Union[str, None] = 'c2d0c6a36954'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('device_name', sa.String(length=50), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('pairing_code', sa.String(length=10), nullable=True),
    sa.Column('pairing_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_device_tokens_pairing_code', 'device_tokens', ['pairing_code'], unique=True, postgresql_where='pairing_code IS NOT NULL')
    op.create_index('ix_device_tokens_user_id', 'device_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_device_tokens_user_id', table_name='device_tokens')
    op.drop_index('ix_device_tokens_pairing_code', table_name='device_tokens', postgresql_where='pairing_code IS NOT NULL')
    op.drop_table('device_tokens')
    # ### end Alembic commands ###
