"""add_progress_tracking

Revision ID: c2d0c6a36954
Revises: bdfeda823326
Create Date: 2026-07-17 08:41:48.945487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2d0c6a36954'
down_revision: Union[str, None] = 'bdfeda823326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progress_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entry_id', sa.Uuid(), nullable=False),
    sa.Column('previous_value', sa.Integer(), nullable=True),
    sa.Column('current_value', sa.Integer(), nullable=False),
    sa.Column('unit', sa.Enum('episodes', 'chapters', 'volumes', 'minutes', 'percentage', name='progress_unit'), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.Enum('update', 'reset', name='progress_event_type'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_progress_events_entry_id_recorded_at', 'progress_events', ['entry_id', 'recorded_at'], unique=False)
    op.add_column('entries', sa.Column('progress_unit', sa.Enum('episodes', 'chapters', 'volumes', 'minutes', 'percentage', name='progress_unit'), nullable=True))
    op.add_column('entries', sa.Column('progress_total', sa.Integer(), nullable=True))
    op.add_column('entries', sa.Column('current_progress', sa.Integer(), nullable=True))
    op.create_check_constraint(
        'ck_entries_progress_total_ge_zero',
        'entries',
        sa.text('progress_total IS NULL OR progress_total >= 0'),
    )
    op.create_check_constraint(
        'ck_entries_current_progress_ge_zero',
        'entries',
        sa.text('current_progress IS NULL OR current_progress >= 0'),
    )
    op.create_check_constraint(
        'ck_entries_progress_lte_total',
        'entries',
        sa.text('progress_total IS NULL OR current_progress IS NULL OR current_progress <= progress_total'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_entries_progress_lte_total', 'entries', type_='check')
    op.drop_constraint('ck_entries_current_progress_ge_zero', 'entries', type_='check')
    op.drop_constraint('ck_entries_progress_total_ge_zero', 'entries', type_='check')
    op.drop_column('entries', 'current_progress')
    op.drop_column('entries', 'progress_total')
    op.drop_column('entries', 'progress_unit')
    op.drop_index('ix_progress_events_entry_id_recorded_at', table_name='progress_events')
    op.drop_table('progress_events')
    # ### end Alembic commands ###
