"""add unique constraint user title type

Revision ID: adc57cb8eb31
Revises: bff6f11d7171
Create Date: 2026-06-12 19:12:25.909808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adc57cb8eb31'
down_revision: Union[str, None] = 'bff6f11d7171'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_entries_user_title_type', 'entries', ['user_id', 'title', 'type'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_entries_user_title_type', table_name='entries')
    # ### end Alembic commands ###
