"""add user_id created_at index on entries

Revision ID: 0447404bbed9
Revises: e3f8a1b92c47
Create Date: 2026-06-19 19:37:57.395191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0447404bbed9'
down_revision: Union[str, None] = 'e3f8a1b92c47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_entries_user_id_created_at', 'entries', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_entries_user_id_created_at', table_name='entries')
    # ### end Alembic commands ###
